style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/binbashar/terraform-waf-owasp
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
